const Storage = {
  orderList: [
    {
      id: 1,
      title: 'Bed',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23133,
      date: '20-05-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 2,
      title: 'Drawer',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
      orderNo: 23103,
      date: '22-07-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 3,
      title: 'Window',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/window.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 4,
      title: 'Installation',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/installation.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 6,
      title: 'Polish',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 7,
      title: 'Window',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/window.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 8,
      title: 'Installation',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/installation.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },
    {
      id: 1,
      title: 'Bed',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23133,
      date: '20-05-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 2,
      title: 'Drawer',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
      orderNo: 23103,
      date: '22-07-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 3,
      title: 'Window',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/window.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 4,
      title: 'Installation',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/installation.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 6,
      title: 'Polish',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 7,
      title: 'Window',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/window.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 8,
      title: 'Installation',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/installation.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      description: 'Fan installation, Fecauly Fan Dimmmer... ',
      price: 250,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
      orderNo: 23132,
      date: '12-03-2020',
      time: '12:30 AM',
      service: ['200', '200', '300'],
      fareCharges: 600,
      totalCharges: 1000,
    },
  ],

  packageList: [
    {
      id: 1,
      title: 'Personal',
      image: require('../images/Home/a5.png'),
      validity: '6 months',
      price: '5999',
      include: [
        'Electration',
        'Plumber',
        'Carpainter',
        'Appliance Repair (Such as Ac Tv Fridge etc)',
      ],
      termCondition: [
        'This package only include service changes',
        'Spare parts will be changed seprately',
        'Package price is inclusive of tax charges',
        '15 visit include the package',
      ],
    },
    {
      id: 2,
      title: 'Basic',
      image: require('../images/Home/a4.png'),
      validity: '6 months',
      price: '7999',
      include: [
        'Electration',
        'Plumber',
        'Carpainter',
        'Appliance Repair (Such as Ac Tv Fridge etc)',
      ],
      termCondition: [
        'This package only include service changes',
        'Spare parts will be changed seprately',
        'Package price is inclusive of tax charges',
        '15 visit include the package',
      ],
    },
    {
      id: 3,
      title: 'Silver',
      image: require('../images/Home/a3.png'),
      validity: '6 months',
      price: '9999',
      include: [
        'Electration',
        'Plumber',
        'Carpainter',
        'Appliance Repair (Such as Ac Tv Fridge etc)',
      ],
      termCondition: [
        'This package only include service changes',
        'Spare parts will be changed seprately',
        'Package price is inclusive of tax charges',
        '15 visit include the package',
      ],
    },
    {
      id: 4,
      title: 'Gold',
      image: require('../images/Home/a2.png'),
      validity: '9 months',
      price: '9999',
      include: [
        'Electration',
        'Plumber',
        'Carpainter',
        'Appliance Repair (Such as Ac Tv Fridge etc)',
      ],
      termCondition: [
        'This package only include service changes',
        'Spare parts will be changed seprately',
        'Package price is inclusive of tax charges',
        '15 visit include the package',
      ],
    },
    {
      id: 5,
      title: 'Platinium',
      image: require('../images/Home/a1.png'),
      validity: '12 months',
      price: '12000',
      include: [
        'Electration',
        'Plumber',
        'Carpainter',
        'Appliance Repair (Such as Ac Tv Fridge etc)',
      ],
      termCondition: [
        'This package only include service changes',
        'Spare parts will be changed seprately',
        'Package price is inclusive of tax charges',
        '15 visit include the package',
      ],
    },
  ],

  basketItem: [
    {
      id: 1,
      title: 'Bed',
      link: 'carpainter',
      quantity: 4,
      rate: 200,
      parentId: 1,
      image: require('../images/Categories/bed.png'),
    },

    {
      id: 2,
      title: 'Drawer',
      link: 'carpainter',
      quantity: 1,
      rate: 500,
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
    },

    {
      id: 3,
      title: 'Window',
      link: 'carpainter',
      quantity: 3,
      rate: 400,
      parentId: 1,
      image: require('../images/Categories/window.png'),
    },

    {
      id: 4,
      title: 'Installation',
      link: 'carpainter',
      quantity: 8,
      rate: 250,
      parentId: 1,
      image: require('../images/Categories/installation.png'),
    },
  ],

  categories: [
    {
      id: 1,
      title: 'Bed',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/bed.png'),
    },

    {
      id: 2,
      title: 'Drawer',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
    },

    {
      id: 3,
      title: 'Window',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/window.png'),
    },

    {
      id: 4,
      title: 'Installation',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/installation.png'),
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/bed.png'),
    },

    {
      id: 6,
      title: 'Polish',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
    },

    {
      id: 7,
      title: 'Window',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/window.png'),
    },

    {
      id: 8,
      title: 'Installation',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/installation.png'),
    },

    {
      id: 5,
      title: 'Cabnet',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/bed.png'),
    },

    {
      id: 6,
      title: 'Polish',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/drawer.png'),
    },

    {
      id: 7,
      title: 'Window',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/window.png'),
    },

    {
      id: 8,
      title: 'Installation',
      link: 'carpainter',
      urdu: 'اردو ٹیکس',
      parentId: 1,
      image: require('../images/Categories/installation.png'),
    },
  ],
};

export default Storage;
